<a href="https://colab.research.google.com/github/DariaHrebeniuk17/numerical_methods/blob/main/%D0%9B%D0%B0%D0%B14_%D0%93%D1%80%D0%B5%D0%B1%D0%B5%D0%BD%D1%8E%D0%BA_%D0%94_%D0%A1_%D0%A4%D0%86%D0%A2_2_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Лабораторна робота 4. Гребенюк Д. С. ФІТ 2-8. Варіант 5
Елементи лінійної алгебри. Розв'язання систем лінійних алгебраїчних рівнянь.


#Завдання 1. Знайти матрицю C = AB - BA
Вар 1(А)

In [3]:
import numpy as np

A = np.array([[1, 2],
             [4, -1]])
B = np.array([[3, 1],
             [2, 4]])

C = np.dot(A, B) - np.dot(B, A)

print(C)

[[ 0  4]
 [-8  0]]


Вар 1 (B)


In [8]:
import numpy as np

A = np.array([[1, 2],
             [4, -1]])
B = np.array([[2, -3],
             [-4, 1]])

C = np.dot(A, B)

print(C)

[[ -6  -1]
 [ 12 -13]]


#Завдання 2. Піднести маьртці до степеня.
вар (1)

In [9]:
import numpy as np

A = np.array([[-1, 2],
              [0, 1]])

A_squared = np.dot(A, A)

print(A_squared)

[[1 0]
 [0 1]]


#Завдання 3. Знайти добуток матриць.
Вар 1

In [10]:
import numpy as np

A = np.array([[3, 5],
              [6, -1]])
B = np.array([[2, 1],
              [-3, 2]])

C = np.dot(A, B)

print(C)

[[-9 13]
 [15  4]]


#Завдання 4. Знайти визначники.
Вар (1)

In [11]:
import numpy as np

matrix = np.array([[2, 3, 4],
                   [1, 0, 6],
                   [7, 8, 9]])

determinant = np.linalg.det(matrix)

print("Визначник матриці:", determinant)

Визначник матриці: 35.00000000000001


# Завдання 5. Обчислити визначники.
Вар (1)

In [12]:
import numpy as np

matrix = np.array([[1, 2, 3, 4],
                   [-2, 1, -4, 3],
                   [3, -4, -1, 2],
                   [4, 3, -2, -1]])

determinant = np.linalg.det(matrix)

print("Визначник матриці:", determinant)

Визначник матриці: 900.0000000000009


# Завдання 6. Знайти обернену матрицю до матриць.
Вар (1)

In [13]:
import numpy as np

matrix = np.array([[1, 2, -3],
                   [0, 1, 2],
                   [0, 0, 1]])

inverse_matrix = np.linalg.inv(matrix)

print("Обернена матриця:")
print(inverse_matrix)

Обернена матриця:
[[ 1. -2.  7.]
 [ 0.  1. -2.]
 [ 0.  0.  1.]]


# Завдання 7. Визначити ранг матриці.
Вар (1)

In [14]:
import numpy as np

matrix = np.array([[1, 2, 3, 4],
                   [3, -1, 2, 5],
                   [1, 2, 3, 4],
                   [1, 3, 4, 5]])

matrix_rank = np.linalg.matrix_rank(matrix)

print("Ранг матриці:", matrix_rank)

Ранг матриці: 2


# Завдання 8.
 Розв'язати систему лінійних рівнянь методом Крамера, матричним методом (тобто обчислити обернену матрицю) і м. Гауса. Потім зробити перевірку за допомогою solve() пакету linalg:
 Варіант 5

In [15]:
import numpy as np

A = np.array([[14, 4, 6],
              [5, -3, 2],
              [10, -11, 5]])
b = np.array([30, 15, 36])

# Метод Крамера
def cramer(A, b):
    det_A = np.linalg.det(A)
    if det_A == 0:
        print("Система не має єдиного розв'язку")
        return
    det_Ax = np.linalg.det(np.column_stack((b, A[:,1], A[:,2])))
    det_Ay = np.linalg.det(np.column_stack((A[:,0], b, A[:,2])))
    det_Az = np.linalg.det(np.column_stack((A[:,0], A[:,1], b)))
    x = det_Ax / det_A
    y = det_Ay / det_A
    z = det_Az / det_A
    return x, y, z

# Матричний метод
def matrix_method(A, b):
    if np.linalg.det(A) == 0:
        print("Система не має єдиного розв'язку")
        return
    A_inv = np.linalg.inv(A)
    x = np.dot(A_inv, b)
    return x

# Метод Гаусса
def gauss_method(A, b):
    x = np.linalg.solve(A, b)
    return x

# Перевіряємо за допомогою solve()
x_cramer, y_cramer, z_cramer = cramer(A, b)
x_matrix, y_matrix, z_matrix = matrix_method(A, b)
x_gauss, y_gauss, z_gauss = gauss_method(A, b)

print("Розв'язок методом Крамера:", x_cramer, y_cramer, z_cramer)
print("Розв'язок матричним методом:", x_matrix, y_matrix, z_matrix)
print("Розв'язок методом Гаусса:", x_gauss, y_gauss, z_gauss)

Розв'язок методом Крамера: 2.0000000000000018 -1.0 0.9999999999999972
Розв'язок матричним методом: 1.9999999999999987 -1.0000000000000004 1.0000000000000018
Розв'язок методом Гаусса: 2.0 -1.0 1.0


# Завдання 2.1.
Вар 5
Створіть прямокутну матрицю А, яка має № рядків і М стовпців з випадковими елементами. Знайдіть суму елементів всієї матриці. Визначте, яку долю в цій сумі складає сума елементів кожного рядка.

In [17]:
import numpy as np

def analyze_matrix(N, M):

  matrix = np.random.rand(N, M)

  total_sum = np.sum(matrix)

  row_sums = np.sum(matrix, axis=1)
  row_percentages = row_sums / total_sum * 100

  return matrix, total_sum, row_percentages

N = 4
M = 5
matrix, total_sum, row_percentages = analyze_matrix(N, M)

print("Матриця:\n", matrix)
print("Загальна сума:", total_sum)
print("Відсоткове співвідношення суми кожного рядка:\n", row_percentages)

Матриця:
 [[0.14357107 0.01080109 0.30560247 0.67752305 0.39151896]
 [0.52765794 0.54530162 0.0090219  0.14558527 0.04973311]
 [0.00431051 0.26795403 0.01637264 0.19710253 0.55822892]
 [0.48138186 0.32748179 0.82002514 0.54289602 0.58250744]]
Загальна сума: 6.604577332334843
Відсоткове співвідношення суми кожного рядка:
 [23.15086281 19.33961515 15.80674375 41.7027783 ]
